### ISSUE TITLE
[Help needed] Distance filter

### ISSUE THREAD

**Issue by nelim** [tananaev/traccar#1570]
Hello Anton, 
First of all to inform that this one is using Vitaly vitalidze/traccar-web#383 web instance.

I have following problem and don't know is it server or device related.
I'm stopping the car at the morning(10:00 o`clock), everything is OK
But after work on 18:00+ after car and gps are started, tracker send one position with old coordinates and old date, before it gets GPS signal/lock and start with new positions.

I have filter.distance 30m in traccar.xml config and no matter that coordinates are the same (it must discard that position) it is in the database, also (maybe related) another strange thing that happens is - <distance> in other field got reset and start from zero? 

Note that filter.distance is working when i drive and stop because i see "INFO: Position filtered from 1" in logs.

I also added new filter.duplicate option on config. But sometimes device sends time 10 or more seconds ahead of last position time, with same gps coordinates so distance filter will be better.

```
mysql> select latitude,longitude,serverTime,time,other from positions where id = 1440;
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| latitude         | longitude        | serverTime          | time                | other                                                                                                                                                        |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 42.1474616666667 | 24.7650883333333 | 2015-12-03 10:10:59 | 2015-12-03 10:10:57 | <info><status>00000000</status><charge>true</charge><ignition>false</ignition><odometer>0</odometer><distance>2833.55</distance><ip>212.5.158.25</ip></info> |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select latitude,longitude,serverTime,time,other from positions where id = 1441;
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| latitude         | longitude        | serverTime          | time                | other                                                                                                                                                  |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| 42.1474616666667 | 24.7650883333333 | 2015-12-03 18:17:23 | 2015-12-03 10:10:57 | <info><status>00000000</status><charge>true</charge><ignition>false</ignition><odometer>0</odometer><distance>0</distance><ip>212.5.158.22</ip></info> |
+------------------+------------------+---------------------+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by tananaev** [comment]
I need to see full logs including those messages. Looking at two random records in the database doesn't really help with finding the problem.

**Comment by nelim** [comment]
```
.....
2015-12-03 10:09:37  INFO: Position filtered from 1
2015-12-03 10:09:49 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383138394e30323434352e37373531453030322e3930383039343534382e34393030303030303030304c303030303030303029
2015-12-03 10:09:49  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:09:45, lat: 42.14698, lon: 24.76292, speed: 1.6, course: 48.5
2015-12-03 10:09:58 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383331344e30323434352e37393830453031392e3030383039353634372e36323030303030303030304c303030303030303029
2015-12-03 10:09:58  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:09:56, lat: 42.14719, lon: 24.76330, speed: 10.3, course: 47.6
2015-12-03 10:10:08 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383638304e30323434352e38303031453032382e3430383130303631372e39303030303030303030304c303030303030303029
2015-12-03 10:10:08  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:10:06, lat: 42.14780, lon: 24.76334, speed: 15.3, course: 17.9
2015-12-03 10:10:18 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383834384e30323434352e38343637453032352e3430383130313636392e32393030303030303030304c303030303030303029
2015-12-03 10:10:18  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:10:16, lat: 42.14808, lon: 24.76411, speed: 13.7, course: 69.3
2015-12-03 10:10:28 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383834334e30323434352e38383134453031342e3530383130323638392e33363030303030303030304c303030303030303029
2015-12-03 10:10:28  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:10:26, lat: 42.14807, lon: 24.76469, speed: 7.8, course: 89.4
2015-12-03 10:10:38 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383737394e30323434352e39303637453030382e363038313033363130392e363530303030303030304c303030303030303029
2015-12-03 10:10:38  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:10:36, lat: 42.14797, lon: 24.76511, speed: 4.6, course: 109.7
2015-12-03 10:10:49 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383537384e30323434352e39313838453031332e323038313034373138382e333030303030303030304c303030303030303029
2015-12-03 10:10:49  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:10:47, lat: 42.14763, lon: 24.76531, speed: 7.1, course: 188.3
2015-12-03 10:10:59 DEBUG: [4275FBFF: 5002 < 212.5.158.25] HEX: 283032373034333634313033344252303031353132303341343230382e383437374e30323434352e39303533453030302e323038313035373138382e363930303030303030304c303030303030303029
2015-12-03 10:10:59  INFO: [4275FBFF] id: 1, time: 2015-12-03 10:10:57, lat: 42.14746, lon: 24.76509, speed: 0.1, course: 188.7
2015-12-03 10:32:01  INFO: [F418B880] connected
2015-12-03 10:32:01 DEBUG: [F418B880: 5001 < 87.252.174.101] HEX: 47455420687474703a2f2f7777772e676f6f676c652e636f6d2f20485454502f312e300d0a486f73743a207777772e676f6f676c652e636f6d0d0a4163636570743a20746578742f68746d6c0d0a557365722d4167656e743a204d6f7a696c6c612f342e302028636f6d70617469626c653b204d53494520362e303b2057696e646f7773204e5420352e31290d0a50726f78792d436f6e6e656374696f6e3a20636c6f73650d0a0d0a
2015-12-03 10:32:17  INFO: [F418B880] disconnected
2015-12-03 10:57:22  INFO: [28B79635] connected
2015-12-03 10:57:22 DEBUG: [28B79635: 5001 < 87.252.174.101] HEX: 474554202f73746174757320485454502f312e310d0a4163636570743a202a2f2a0d0a557365722d4167656e743a2058656e75204c696e6b20536c657574682f312e332e380d0a486f73743a203139352e3233382e38352e3133333a353030310d0a43616368652d436f6e74726f6c3a206e6f2d63616368650d0a0d0a
2015-12-03 10:32:17  INFO: [F418B880] disconnected
2015-12-03 10:57:22  INFO: [28B79635] connected
2015-12-03 10:57:22 DEBUG: [28B79635: 5001 < 87.252.174.101] HEX: 474554202f73746174757320485454502f312e310d0a4163636570743a202a2f2a0d0a557365722d4167656e743a2058656e75204c696e6b20536c657574682f312e332e380d0a486f73743a203139352e3233382e38352e3133333a353030310d0a43616368652d436f6e74726f6c3a206e6f2d63616368650d0a0d0a
2015-12-03 10:57:52  INFO: [28B79635] disconnected
2015-12-03 11:11:19  INFO: [8622E8E6] connected
2015-12-03 11:11:19 DEBUG: [8622E8E6: 5022 < 87.252.174.101] HEX: 47455420687474703a2f2f7777772e676f6f676c652e636f6d2f20485454502f312e300d0a486f73743a207777772e676f6f676c652e636f6d0d0a4163636570743a20746578742f68746d6c0d0a557365722d4167656e743a204d6f7a696c6c612f342e302028636f6d70617469626c653b204d53494520362e303b2057696e646f7773204e5420352e31290d0a50726f78792d436f6e6e656374696f6e3a20636c6f73650d0a0d0a
2015-12-03 11:11:19  WARN: Unknown device - 474703a2f2f7777 (87.252.174.101)
2015-12-03 11:11:34  INFO: [8622E8E6] disconnected
2015-12-03 13:33:06  INFO: Shutting down server...
2015-12-03 13:33:08  INFO: [4275FBFF] disconnected
2015-12-03 13:44:24  INFO: Operating system name: Linux version: 2.6.32-5-openvz-amd64 architecture: amd64
2015-12-03 13:44:24  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 24.45-b08
2015-12-03 13:44:24  INFO: Memory limit heap: 725mb non-heap: 130mb
2015-12-03 13:44:24  INFO: Character encoding: UTF-8 charset: UTF-8
2015-12-03 13:44:24  INFO: Version: 3.2-SNAPSHOT
2015-12-03 13:44:33  INFO: Starting server...
2015-12-03 14:40:01  INFO: [383D995B] connected
2015-12-03 14:40:01 DEBUG: [383D995B: 5022 < 87.252.174.101] HEX: 474554202f73746174757320485454502f312e310d0a4163636570743a202a2f2a0d0a557365722d4167656e743a2058656e75204c696e6b20536c657574682f312e332e380d0a486f73743a203139352e3233382e38352e3133333a353032320d0a43616368652d436f6e74726f6c3a206e6f2d63616368650d0a0d0a
2015-12-03 14:40:01  WARN: Unknown device - 374617475732048 (87.252.174.101)
2015-12-03 14:40:31  INFO: [383D995B] disconnected
2015-12-03 18:17:20  INFO: [465B77D6] connected
2015-12-03 18:17:21 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344250303030303030323730343336343130333448534f29
2015-12-03 18:17:21 DEBUG: [465B77D6: 5002 > 212.5.158.22] HEX: 283032373034333634313033344150303148534f29
2015-12-03 18:17:22 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e383437374e30323434352e39303533453030302e323038313035373138382e363930303030303030304c303030303030303029
2015-12-03 18:17:23  INFO: [465B77D6] id: 1, time: 2015-12-03 10:10:57, lat: 42.14746, lon: 24.76509, speed: 0.1, course: 188.7
2015-12-03 18:17:34 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e383136334e30323434352e38313236453030312e313136313733343333392e353130303030303030304c303030303030303029
2015-12-03 18:17:34  INFO: [465B77D6] id: 1, time: 2015-12-03 18:17:34, lat: 42.14694, lon: 24.76354, speed: 0.6, course: 339.5
2015-12-03 18:17:44 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e383136364e30323434352e38313139453030302e363136313734343333392e353130303030303030304c303030303030303029
2015-12-03 18:17:44  INFO: Position filtered from 1
2015-12-03 18:17:54 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e383134374e30323434352e37393738453030362e313136313735343233332e343330303030303030304c303030303030303029
2015-12-03 18:17:54  INFO: Position filtered from 1
2015-12-03 18:18:04 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e383134364e30323434352e37393236453030342e363136313830343234372e393030303030303030304c303030303030303029
2015-12-03 18:18:04  INFO: Position filtered from 1
2015-12-03 18:18:14 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e373833364e30323434352e37383338453033342e383136313831343138302e393230303030303030304c303030303030303029
2015-12-03 18:18:14  INFO: [465B77D6] id: 1, time: 2015-12-03 18:18:14, lat: 42.14639, lon: 24.76306, speed: 18.8, course: 180.9
2015-12-03 18:18:25 DEBUG: [465B77D6: 5002 < 212.5.158.22] HEX: 283032373034333634313033344252303031353132303341343230382e373130334e30323434352e37383538453034332e333136313832353137392e343730303030303030304c303030303030303029
2015-12-03 18:18:25  INFO: [465B77D6] id: 1, time: 2015-12-03 18:18:25, lat: 42.14517, lon: 24.76310, speed: 23.4, course: 179.5

....
```
Maybe this server shutdown is the problem ?

**Comment by tananaev** [comment]
It could be the problem if you don't use `database.selectLatestPositions` query.

**Comment by nelim** [comment]
I have: (note it is with traccar-web and it is different of my main server)
```
<entry key='database.selectLatestPositions'>
    SELECT * FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
</entry>
```

```
mysql> SELECT id,address,device_id FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
+------+------------------------------------------------------+-----------+
| id   | address                                              | device_id |
+------+------------------------------------------------------+-----------+
| 1310 | 2 ul. "Elbasan", Plovdiv, Plovdiv, BG                |         2 |
| 1694 | 10 ul. "Kapitan Georgi Tsanev", Plovdiv, Plovdiv, BG |         1 |
+------+------------------------------------------------------+-----------+
2 rows in set (0.01 sec)
```
latestPosition_id in devices is accurate

maybe it is some query related.. because i'm sure i dont have this problem with your interface and same device.. also distance on json attributes does not reset.. just cant find where is the problem in this setup :)

**Comment by tananaev** [comment]
Can you please provide your config file.

**Comment by nelim** [comment]
http://nelim.han.bg/traccar.xml

**Comment by tananaev** [comment]
The link returns `nelim.han.bg crypted` message.

**Comment by nelim** [comment]
You are just damn fast.. :) i've edited it

**Comment by tananaev** [comment]
I guess columns in your database structure don't match names that `database.selectLatestPositions` expects.

**Comment by nelim** [comment]
```
mysql> SELECT * FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
+------+------------------------------------------------------+------------------+--------+------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------+-------+----------+---------------------+-------+---------------------+-------+-----------+
| id   | address                                              | altitude         | course | latitude   | longitude   | other                                                                                                                                   | power | protocol | serverTime          | speed | time                | valid | device_id |
+------+------------------------------------------------------+------------------+--------+------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------+-------+----------+---------------------+-------+---------------------+-------+-----------+
| 1310 | 2 ul. "Elbasan", Plovdiv, Plovdiv, BG                | 184.800003051758 |      0 | 42.1474735 | 24.73716037 | <info><battery>64.0</battery><distance>4629.69</distance><ip>212.5.158.8</ip></info>                                                    |  NULL | osmand   | 2015-12-01 19:42:11 |     0 | 2015-12-01 19:42:11 |      |         2 |
| 1694 | 10 ul. "Kapitan Georgi Tsanev", Plovdiv, Plovdiv, BG |                0 |  42.32 |    42.1476 |   24.736755 | <info><status>00000000</status><charge>true</charge><ignition>false</ignition><distance>11027.77</distance><ip>212.5.158.29</ip></info> |  NULL | tk103    | 2015-12-04 19:16:36 |     0 | 2015-12-04 19:16:34 |      |         1 |
+------+------------------------------------------------------+------------------+--------+------------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------+-------+----------+---------------------+-------+---------------------+-------+-----------+
2 rows in set (0.00 sec)
```

**Comment by tananaev** [comment]
This is expected structure:
<pre>CREATE TABLE position (
        id INT PRIMARY KEY AUTO_INCREMENT,
        protocol VARCHAR(128),
        deviceId INT NOT NULL,
        serverTime TIMESTAMP NOT NULL,
        deviceTime TIMESTAMP NOT NULL,
        fixTime TIMESTAMP NOT NULL,
        valid BIT NOT NULL,
        latitude DOUBLE PRECISION NOT NULL,
        longitude DOUBLE PRECISION NOT NULL,
        altitude FLOAT NOT NULL,
        speed FLOAT NOT NULL,
        course FLOAT NOT NULL,
        address VARCHAR(512),
        attributes VARCHAR(4096) NOT NULL,
        FOREIGN KEY (deviceId) REFERENCES device (id) ON DELETE CASCADE);</pre>

At least `device_id`, `time` and `other` should be changed.

**Comment by nelim** [comment]
@tananaev Thank you for your time, I'm not sure i can change this table without broke web interface.
@vitalidze Can you help with that, it continues from vitalidze/traccar-web#383.

**Comment by nelim** [comment]
@tananaev But while driving, as you can see in logs - filter.distance is working just fine, maybe latestPosition does no matter if device is not discconnected?

**Comment by tananaev** [comment]
You don't need to change tables. You can just rename them in the query like this:

<pre>SELECT device_id AS deviceId FROM positions;</pre>

**Comment by vitalidze** [comment]
First of all, I don't think the `database.selectLatestPositions` affects this issue much because it is only used at the traccar startup. Then positions are updated right after they were received independently of the underlying database schema. So probably you may miss at least one position, or have at least one duplicate. I don't think this is a big issue, but anyway.

Then, there is no need to change schema to make the query match the original traccar's schema. You may just use the column aliases, something like @tananaev says.

**Comment by vitalidze** [comment]
Probably the full query may be:

````sql
SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, time AS fixTime, 
valid, latitude, longitude, altitude, speed, course, address, other AS attributes 
FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
````

I haven't tried it. But again, I don't think this is the main reason of this issue.

**Comment by nelim** [comment]
I'll try this and write again after testing, thank you both for your time.
@vitalidze Yes, for sure it is not a big issue, it is just related with my Drives/Stops report and offline positions, because after every offline position i get one more(on next start, which is not marked as offline) and it merges all the time as "Moving" on report, and i need to delete them to make reports OK. It is not big issue and i can do a workaround for sure, but it will be better if i can filter them, instead of deleting them after :)

Thank you both and have a good night, I've changed this query but will have information after couple of drivings and some research :) Wish you a good night/day (depending your timezones) :)

:+1:

**Comment by nelim** [comment]
Issue is fixed, first valid position with 2015-12-04 with same coordinates is filtered correctly
Thanks @tananaev

@vitalidze I think this must be corrected in installation guide, otherwise this  ```database.selectLatestPositions``` is incorrect and if server is restarted, it is useless?
With that from your post it is ok
```
SELECT id, protocol, device_id AS deviceId, serverTime, time AS deviceTime, time AS fixTime, 
valid, latitude, longitude, altitude, speed, course, address, other AS attributes 
FROM positions WHERE id IN (SELECT latestPosition_id FROM devices);
```

```
2015-12-05 14:29:26  INFO: [3F9BB1C9] connected
2015-12-05 14:29:27 DEBUG: [3F9BB1C9: 5002 < 212.5.158.16] HEX: 283032373034333634313033344250303030303030323730343336343130333448534f29
2015-12-05 14:29:27 DEBUG: [3F9BB1C9: 5002 > 212.5.158.16] HEX: 283032373034333634313033344150303148534f29
2015-12-05 14:29:28 DEBUG: [3F9BB1C9: 5002 < 212.5.158.16] HEX: 283032373034333634313033344252303031353132303441343230382e383539324e30323434342e32313432453030352e3731373136353437342e31303030303030303030304c303030303030303029
2015-12-05 14:29:28  INFO: Position filtered from 1
2015-12-05 14:29:59 DEBUG: [3F9BB1C9: 5002 < 212.5.158.16] HEX: 283032373034333634313033344252303031353132303541343230382e383134384e30323434342e33323831453033302e363132323935393132302e383930303030303030304c303030303030303029
2015-12-05 14:29:59  INFO: [3F9BB1C9] id: 1, time: 2015-12-05 14:29:59, lat: 42.14691, lon: 24.73880, speed: 16.5, course: 120.9
2015-12-05 14:30:09 DEBUG: [3F9BB1C9: 5002 < 212.5.158.16] HEX: 283032373034333634313033344252303031353132303541343230382e383130364e30323434342e33373930453032372e363132333030393131322e303330303030303030304c303030303030303029
```

**Comment by vitalidze** [comment]
I still don't understand why it helps. But ok, I will update the instructions.
