### ISSUE TITLE
Can't create users if disabled

### ISSUE THREAD

**Issue by netomx** [tananaev/traccar#1670]
I know the title is confusing, but on an old version (probably 2), I could create users in an admin session but registers were disabled, and now I can't. Is it a feature or a bug?

Thanks

**Comment by tananaev** [comment]
There was a bug. It's fixed now as far as I remember.

**Comment by netomx** [comment]
So, I cannot create users if I'm in an admin session and the server has disabled registrations?

**Comment by tananaev** [comment]
You should be able if you have the fixed build.

**Comment by netomx** [comment]
The one I downloaded earlier? Like an hour?

**Comment by tananaev** [comment]
Yes, that one should contain the fix.

**Comment by netomx** [comment]
Tried:

```Registration disabled - SecurityException (PermissionsManager:95 < UserResource:51 < ...)```

**Comment by tananaev** [comment]
Fixed the problem. Here is a new build:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by netomx** [comment]
Thanks, will test shortly

**Comment by sharkile** [comment]
I just found out that this bug is still present in traccar 3.4

**Comment by tananaev** [comment]
@sharkile, I just double-checked and everything works correctly for me on 3.4.

**Comment by sharkile** [comment]
That's weird, registration is disabled and if I try to add another user I got this pop-up.
![traccar](https://cloud.githubusercontent.com/assets/17736615/13627364/1d2cc858-e587-11e5-99dd-0cd613e35100.png)
If you point me to the right log I'll gladly share it with you if needed.

**Comment by tananaev** [comment]
How did you install version 3.4? You are definitely using old binary.

**Comment by sharkile** [comment]
It was a fresh install. I stopped traccar, dropped the database, uninstalled the daemon and deleted the installation directory, then I just unzipped the 3.4 file, ran the installation script and set traccar to use MySQL.

I also notice that whenever I run `./traccar status` I get the _traccar is not running_ message even though it is actually running, I don't know if that has anything to to with the issue.

**Comment by tananaev** [comment]
Please provide MD5 hash of the `tracker-server.jar` file.

**Comment by sharkile** [comment]
76434ec6f247da409f9519e252d0fb11

2016-03-09 0:17 GMT-07:00 Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
That's correct hash, but line numbers in the error don't match the code, so we must be missing something.
