### ISSUE TITLE
On demand reverse geocoding not saving addrrsses

### ISSUE THREAD

**Issue by karls4** [tananaev/traccar#3756]
When running a trips report the on demand reverse geocoding works great but if I run that report again it has to request them addresses again.

It would be great if we could save these to save requests and costs.

**Comment by Abyss777** [comment]
As a partial solution, you can enable geocoder cache (`geocoder.cacheSize`). It is in memory address cache, works until server restart.
It might help to save you some requests.

**Comment by karls4** [comment]
Hi @Abyss777, when running a routes report the addresses all come back as undefined.

Is it possible to request these when running the report the same as the trips report works?

Thanks

**Comment by Abyss777** [comment]
No, it is currently not implemented.
Why do you need this? Such reports will produce a lot of geocoding requests and slow down route report generating.

**Comment by karls4** [comment]
It still works out cheaper in the long run to request these and save them instead of saving every address that comes into the server.

Would it be possible to implement this and turn it on/off using a parameter in the config?

Thanks

**Comment by karls4** [comment]
![image](https://user-images.githubusercontent.com/22108543/36479625-3d139af4-1701-11e8-95e2-2aaa917ff64f.png)

As you can see the amount of reverse geocoding is considerably less since I have implemented your changes to work with onrequest which is great.

**Comment by Abyss777** [comment]
I still do not understand why do you need address in every position in Route report? You can click on desired and request it, but why you need all?

**Comment by karls4** [comment]
I do get what you are saying but some users/use cases are different from what you imagine.

Would this be something you would be willing to implement?

**Comment by tananaev** [comment]
Doing reverse geocoding for every location would most likely cause request to timeout in browser because it will require a lot of request to third party service.

**Comment by tananaev** [comment]
If you have failing reports, it should probably fixed first instead. Is there any other valid reason?

**Comment by tshelver** [comment]
I run my own custom reports on data extracted from Traccar.  We use a Nominatim local database for reverse coding, installed on the same server.  Much faster than lookups across the internet.
